name: Build
on:
  push:
    branches:
      - main
    paths: # only trigger build for actual code changes, i.e. readme and other changes don't cause that issues
      - 'src/**'
      - 'eny.nimble'
      - '.github/workflows/**'

jobs:
  build-win-debug:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      
      - name: Get git short hash
        id: git_short_hash
        run: echo "result=$(git rev-parse --short "${{ github.sha }}")" >> $GITHUB_OUTPUT
        shell: bash
      - uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: '2.2.2'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Packages
        run: nimble install -Y -d

      - name: Build for Windows
        run: nimble build -d:EnyCommitText=${{steps.git_short_hash.outputs.result}}
      
      - name: Set resources on files with rcedit
        uses: Bioblaze/rcedit-action@main
        with:
          directory-path: './'
          file-types: 'exe'
          set-icon: 'true'
          exe-file-name: 'eny.exe'
          ico-file-path: './assets/eny/eny.ico'
          file-version: '0.1.0'
  
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: eny
          path: |
            eny.exe
            assets/   
            content/